/**
 * E2E tests for AC-1: Exercise cards render on page load.
 * Issue 6 — E2E-01, E2E-02
 * Issue 7 — E2E-03
 */

import { test, expect } from '@playwright/test';

const EXERCISES = ['Squat', 'Bench Press', 'Deadlift', 'Overhead Press', 'Bent-over Row'];

test.describe('Issue 6 — AC-1: All 5 exercises render in correct order', () => {
  test('E2E-01: all 5 exercise headings appear in correct DOM order on load', async ({ page }) => {
    await page.goto('/');

    // Use heading role to avoid matching history table cells
    for (const name of EXERCISES) {
      await expect(page.getByRole('heading', { name, exact: true })).toBeVisible();
    }

    // Verify DOM order of headings
    const headingTexts = await page.$$eval('h3', (els) => els.map((el) => el.textContent?.trim() ?? ''));
    const ordered = headingTexts.filter((t) => EXERCISES.includes(t));
    expect(ordered).toEqual(EXERCISES);
  });

  test('E2E-02: each exercise card has Weight, Sets, Reps inputs and a Log button', async ({ page }) => {
    await page.goto('/');

    // Use specific IDs generated by slugify(exerciseName): name.toLowerCase().replace(/\s+/g, '-')
    const slugs: Record<string, string> = {
      'Squat': 'squat',
      'Bench Press': 'bench-press',
      'Deadlift': 'deadlift',
      'Overhead Press': 'overhead-press',
      'Bent-over Row': 'bent-over-row',
    };

    for (const exercise of EXERCISES) {
      const slug = slugs[exercise];
      const card = page.locator('article').filter({ has: page.locator(`#${slug}-weight`) });
      await expect(page.locator(`#${slug}-weight`)).toBeVisible();
      await expect(page.locator(`#${slug}-sets`)).toBeVisible();
      await expect(page.locator(`#${slug}-reps`)).toBeVisible();
      await expect(card.getByRole('button', { name: /log/i })).toBeVisible();
    }
  });
});

test.describe('Issue 7 — AC-1: History table visible on load', () => {
  test('E2E-03: history table is present in DOM on initial load', async ({ page }) => {
    await page.goto('/');
    const table = page.getByRole('table');
    await expect(table).toBeVisible();
    await expect(page.getByRole('columnheader', { name: /date/i })).toBeVisible();
  });
});
